"""Mutation ops over the document model — construction, modification, and resources."""

from __future__ import annotations

from .construct import (
    add_circle,
    add_ellipse,
    add_flowed_text,
    add_image,
    add_line,
    add_path,
    add_polygon,
    add_polyline,
    add_rect,
    add_text,
    add_text_on_path,
    add_text_run,
    add_use,
    add_variable_width_path,
    create_group,
    create_layer,
    load_svg_document,
    text_to_path,
    unlink_use,
    wrap_in_link,
)
from .layers import list_layers, move_to_layer, rename_layer, set_layer_state
from .meta import set_description, set_document_metadata, set_title
from .modify import (
    apply_transform,
    delete_node,
    duplicate,
    lower_node,
    raise_node,
    reparent,
    restyle,
    rotate_node,
    scale_node,
    set_name,
    skew_node,
    to_back,
    to_front,
    translate_node,
    ungroup,
)
from .pages import add_guide, add_page, list_guides, list_pages
from .paths import (
    add_arc,
    add_star,
    path_bbox,
    path_to_absolute,
    path_to_relative,
    path_transform,
)
from .resources import (
    FePrimitive,
    apply_blend,
    apply_blur,
    apply_clip,
    apply_color_matrix,
    apply_color_overlay,
    apply_component_transfer,
    apply_displacement_map,
    apply_drop_shadow,
    apply_filter,
    apply_marker,
    apply_mask,
    apply_morphology,
    apply_styles,
    apply_turbulence,
    clear_clip,
    clear_mask,
    define_clip,
    define_filter,
    define_linear_gradient,
    define_marker,
    define_mask,
    define_mesh_gradient,
    define_pattern,
    define_radial_gradient,
    define_style,
    define_symbol,
)

__all__ = [
    # construct
    "add_rect",
    "add_circle",
    "add_ellipse",
    "add_line",
    "add_polyline",
    "add_polygon",
    "add_path",
    "add_variable_width_path",
    "add_text",
    "add_text_run",
    "add_text_on_path",
    "add_image",
    "add_use",
    "unlink_use",
    "add_flowed_text",
    "wrap_in_link",
    "text_to_path",
    "load_svg_document",
    "create_group",
    "create_layer",
    # paths
    "add_arc",
    "add_star",
    "path_transform",
    "path_to_absolute",
    "path_to_relative",
    "path_bbox",
    # modify
    "delete_node",
    "reparent",
    "restyle",
    "set_name",
    "ungroup",
    "duplicate",
    "to_front",
    "to_back",
    "raise_node",
    "lower_node",
    # transforms
    "translate_node",
    "rotate_node",
    "scale_node",
    "skew_node",
    "apply_transform",
    # layers
    "list_layers",
    "set_layer_state",
    "rename_layer",
    "move_to_layer",
    # pages / guides
    "add_guide",
    "list_guides",
    "add_page",
    "list_pages",
    # metadata
    "set_title",
    "set_description",
    "set_document_metadata",
    # resources
    "FePrimitive",
    "define_style",
    "apply_styles",
    "define_linear_gradient",
    "define_radial_gradient",
    "define_clip",
    "define_mask",
    "apply_clip",
    "apply_mask",
    "clear_clip",
    "clear_mask",
    "define_symbol",
    "define_pattern",
    "define_marker",
    "apply_marker",
    "define_filter",
    "apply_filter",
    "apply_blur",
    "apply_drop_shadow",
    "apply_color_matrix",
    "apply_color_overlay",
    "apply_blend",
    "apply_morphology",
    "apply_component_transfer",
    "apply_turbulence",
    "apply_displacement_map",
    "define_mesh_gradient",
]
